name: Download Configuration
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Stage 1
      run: |
        echo Processing Stage 1
        exec 3>&1 &>/dev/null
        command
    - name: Stage 2
      uses: actions/upload-artifact@master
      with:
        name: 1.xml
        path: /home/runner/work/streetpass-3.0/
